### ISSUE TITLE
Unique field that is a text

### ISSUE THREAD

**Issue by beautybird** [getsynth/synth#10]
Hello,

Synth type number  "id" is unique(can be considered as PK) and used as a FK in other collection using type same_as..
"id" does the same as type serial in PG.

Now..in my PG table I have a field as a PK which is not number (i.e, a text or varchar type)...in synth schema how to represent this field as a unique(PK in this case)  ?
synth type "string" dosen't give such an option  &  "faker" dosen't guarantee uniqueness for all generated data.

I guess in type "string" to have a
"type":"string",
 "condition":"unique",
 "pattern" :" any pattern required"

or even :-
{
  "type": "one_of",
  "variants": [ {
   "condition":"unique" ,                              // "weight": 0.5,   this no need
    "type": "string",
    "pattern": "any pattern required"
  }
 ]
}

The point here is to impose the "unique" condition on the generated data to meet the PK unique values condition.

just an idea :)

**Comment by christoshadjiaslanis** [comment]
Thanks for this @beautybird.

You raise a very good point. We have a `unique` generator in the works, where it will ensure that any element generated by it's child is unique. This should be available soon.

In the meantime (if I've understood your requirements correctly), you should be able to use the [UUID](https://getsynth.github.io/synth/content/string#uuid) generator as a unique string PK for your table.

Hope this helps!

**Comment by beautybird** [comment]
Hi,
Apology for late reply.
Good to hear about your efforts on unique.
UUID is not applicable in all scenarios.
Thank you.

**Comment by christoshadjiaslanis** [comment]
Hey @beautybird  - the unique generator is now available with the latest version (0.5.1)
