### ISSUE TITLE
"$" copies when pressing "copy" 

### ISSUE THREAD

**Issue by dilipsabherwal** [getsynth/synth#12]
**Describe the bug**
 "$" copies when pressing "copy"  in "synth/docs/docs/getting_started/hello-world.md"

**To Reproduce**
Press copy in https://getsynth.github.io/synth/getting_started/hello-world
"$" copies as well as string 

**Expected behavior**
String should be copied and "$" should be omitted

**Comment by christoshadjiaslanis** [comment]
Thanks for this @dilipsabherwal !

Good point. I think there are a few more places in the docs where this is the case. I'll get on it ASAP.

**Comment by christoshadjiaslanis** [comment]
Fixed in latest commit. Thanks again @dilipsabherwal !
