### ISSUE TITLE
Allow unbounded `number`s

### ISSUE THREAD

**Issue by llogiq** [getsynth/synth#145]
**Required Functionality**
Currently `number` types can only be `range`, `categorical` (for integers) and `constant` (also some can be `Id`). There is no easy way to specify generating arbitrary numbers

**Proposed Solution**
Consider adding an `unbounded` variant that will generate any valid number of the given type, alternatively make serde use the range default if no argument at all is given.

**Use case**
Simplify the default, allow getting arbitrary numbers without much hassle

**Comment by brokad** [comment]
Great idea @llogiq! As a matter of fact, from discussions we had, I think we can kill two birds with one stone with #146. Let me know what you think and if it does indeed address this along the lines of your second proposed solution (the default one).
