### ISSUE TITLE
Support JSON Lines format (.jsonl)

### ISSUE THREAD

**Issue by mrsarm** [getsynth/synth#183]
**Required Functionality**
Currently JSON is supported and CSV is going to be supported (https://github.com/getsynth/synth/issues/33), well [JSON Lines](https://jsonlines.org/) is like CSV, but with the power of JSON, it's very used to export big chunks of data with columns with complex values not supported by CSV, and where JSON is inefficient. Because one line is one record like CSV, it's much efficient than JSON to import, and it's used among other things because it's really easy to build a JSON line from a JSON file that is filtered / post-processed with tools like `jq`.

**Proposed Solution**
Support it, and because only one type of data like CSV is supported, either assume that the file only has one type of data, or allow to set as argument the name of the column that determine the type of data (this also applies to CSV). E.g. in CouchDB there are no tables or collections, everything is store in the same database, but by convention the field "type" is used to discriminate what is the type of the record: users, transactions, claims...

**Use case**
As mentioned above, it's easy to generate and work with JSON Lines. E.g. here is a transformation example made with `jq`. :

```sh
$ echo '{ "transactions": [ {"tx":123, "amount": 100, "cust_id": 444}, {"tx":123, "amount": 100, "cust_id": 444} ]  }' \
    | jq '.transactions[]|{tx:.tx,val:.amount}' -c
{"tx":123,"val":100}
{"tx":123,"val":100}
```

Another example: although the documentation of `mongoexport` says it export to JSON, in reality the output format is JSON Lines.

**Comment by christoshadjiaslanis** [comment]
Hey @mrsarm thanks for this. 

There is the question of `CouchDB` integration in general which we can build an integration for (perhaps opening a separate issue for this). 

On the topic of JSON lines I think this makes a lot of sense. I assume it would work on a per collection basis, i.e.:

```console
synth generate my_namespace --collection transactions --to jsonl
{"tx": 123, "val"100}
...
```

I wonder how this would work for a namespace, with multiple collections.

**Comment by mrsarm** [comment]
Yes, the syntax you propose for generation makes sense, and should be supported when importing too. CSV and JSON Lines would be treated in the same way, using the `--collection` argument to set the collection/table.

> I wonder how this would work for a namespace, with multiple collections.

Yes, for JSON Line one of the field can be used to determine the collection (perfect match for data imported or exported from Couch where by convention the "type" field is used for that, but can applies to other sources too). But that isn't the case for CSV, where you have fixed columns, so each collection needs its own file.
