### ISSUE TITLE
Namespace name not reported in error

### ISSUE THREAD

**Issue by christos-h** [getsynth/synth#204]
**Describe the bug**
When an error is reported at a namespace, the file specified is reported instead of the actual name of the namespace (i.e. the directory name)

```
synth generate . | jq
Error: At namespace "."

Caused by:
...
```

**To Reproduce**
Create any invalid schema and run:
```
synth generate .
```

**Expected behavior**
```
synth generate . | jq
Error: At namespace "<namespace_name>"

Caused by:
...
```

**Environment (please complete the following information):**
 - Linux
 - 0.5.6

**Comment by sa1** [comment]
I wasn't able to test a fix. Could you provide me with an invalid schema?

All my attempts to invalidate the schema gave me another error:


```
Error: Unable to open the namespace

Caused by:
    0: at file ./users.json
    1: Failed to parse collection
    2: unknown variant `email`, expected one of `null`, `bool`, `number`, `string`, `array`, `object`, `same_as`, `one_of`, `series`, `unique` at line 29 column 1`
```
