### ISSUE TITLE
OSX: 0.6.0 build does not contain executable synth binary, 0.5.6 build does

### ISSUE THREAD

**Issue by billatmakeit** [getsynth/synth#216]
Mac OSX details:
Darwin MacBook-Pro.local 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64

Example (0.6.0 build):
$ file synth
synth: data
$ ls -l synth*
-rwxr-xr-x@ 1 (userid_masked)  staff  19691080 Oct 18 15:57 synth
-rw-r--r--@ 1 (userid_masked)  staff   3548972 Oct 19 14:43 synth-macos-latest-x86_64.tar.gz

Example (0.5.6 build):
$ file synth
synth: Mach-O 64-bit executable x86_64
$ ls -ld ./synth*
-rwxr-xr-x@ 1 (userid_masked)  staff  19416944 Sep 30 09:36 ./synth
-rw-r--r--@ 1 (userid_masked)  staff   6874126 Oct 19 14:46 ./synth-macos-latest-x86_64.tar.gz

Procedure to replicate:
1) Download 0.6.0 tar.gz file
2) tar xzf synth-macos-latest-x86_64.tar.gz
3) file synth

**Comment by chesedo** [comment]
So this happens because of the `tar` installed for the mac agent as can be seen [here](https://github.com/chesedo/synth/runs/4116091121?check_suite_focus=true). This is a known issue as documented in actions/virtual-environments#2619 and I'll create PR with one of the suggestions
