### ISSUE TITLE
bug: update `date_time` examples

### ISSUE THREAD

**Issue by chesedo** [getsynth/synth#267]
**Describe the bug**
Similar to #257, the use of the `date_time` is broken for the playground examples on the website.

**To Reproduce**
1. Go to the [examples](https://www.getsynth.com/#snippets) on the website
2. Click "Run" for the "Time series data" or "Event logs data" example

**Expected behavior**
The output should update like it does for the "Relational data" example

**Additional context**
Inspecting the page and viewing the network logs shows the playground returned the following error:
```
"unknown variant `date_time`, expected one of `pattern`, `faker`, `categorical`, `serialized`, `uuid`, `truncated`, `sliced`, `format`, `constant` at line 24 column 1"
```

This is because of the update in #184

**Comment by christoshadjiaslanis** [comment]
Maybe it's about time we add an automated step to run all the documentation examples and fail if any of them cannot be processed (as per above).

**Comment by chesedo** [comment]
Interesting idea :thinking: If we are lucky then we can maybe just run all *.json files through `synth generate`... but probably very unlikely
