### ISSUE TITLE
Double quotes instead single quotes for JSON

### ISSUE THREAD

**Issue by davidseidel** [getsynth/synth#28]
Synth uses single quotes to serialize objects. This leads to errors, when I try to insert these object into a PostgreSQL-DB, because it supposes double quotes for property names in object.

**Comment by llogiq** [comment]
Thank you for bringing this to our attention! Changing the quotes should be easy enough. Note however that the output may still contain single quotes, and I am not sure if they are correctly escaped yet (Postgres also accepts JSON with correctly escaped single quotes, to the best of my knowledge).

We should probably add something to this effect in the postgres export integration test.

**Comment by brokad** [comment]
I believe this was solved with #107 since now exports preserve database-native types, including (in the case of postgres) the JSON type; whereas before we were just dumping a string content into a query.

Can @llogiq or @christoshadjiaslanis confirm this is true?

**Comment by christoshadjiaslanis** [comment]
@brokad yes thats right.

**Comment by brokad** [comment]
Thank you!

Give it a shot with latest @davidseidel, let us know if it still does not work :smile:

Closing this for now.
