### ISSUE TITLE
Use parameterized Statements for Postgres export

### ISSUE THREAD

**Issue by llogiq** [getsynth/synth#30]
**Required Functionality**
Currently, the postgres export statements are build as strings. See [postgres.sql:91](https://github.com/getsynth/synth/blob/master/synth/src/cli/postgres.rs#L91) and following.

**Proposed Solution**
Make it use a prepared statement instead. This requires implementing `ToSql` on our [`Value`]() implementation and creating a function that builds the SQL statement from a given list of columns for the namespace.

**Use case**
Not only will this make the export faster by removing the Value → String → Value roundtrip, it will also reduce the avenues for errors because of failing to escape data (if someone manages to generate [bobby tables](https://xkcd.com/327)).

**Comment by juniorbassani** [comment]
Hey! I believe I can work on this. I'm just not quite sure I understand about _ToSql_. Is it a trait from another library? One to be implemented in Synth itself?

**Comment by OLUWAMUYIWA** [comment]
`postgres` has an implementation of `ToSql`  that may be enabled by including it in the features list. With that, do we still need to re-implement `ToSql`?

**Comment by llogiq** [comment]
In the lossless sampling PR, we switch to sqlx, along with implementing it's `Type` and `Encode` traits. Yesterday I split out the export half of the PR so it's easier to review. Expect it to be merged next week.
