### ISSUE TITLE
Feature: CSV import/export

### ISSUE THREAD

**Issue by llogiq** [getsynth/synth#33]
**Required Functionality**
An import and export of CSV files.

**Proposed Solution**
The CSV format has some surprising complexity. Nonetheless, an import could at least use headers (if any) of a CSV file and try to match certain things about the values (e.g. are they all digits?). The export should have an option to declare the delimiter and perhaps quoting / escaping.

**Use case**

* Creating a schema (that can later be refined) from a set of CSV files
* Generating a set of CSV files from a schema.

**Comment by ade-sede** [comment]
I'm a total stranger to the project, and from outside the box, the first solution that comes to mind is converting CSV <-> JSON.

I assume the internal representation is some nested Structs and Enums.
Parsing the CSV into this internal representation could be more bothersome than simply re-using the existing logic for parsing from JSON to internal representation.

As someone who has not read all the source code yet / doesn't use synth, I'd say the only reasons not to do this are
- Extremely big volume of files to process making the process too time consuming.
- Some incompatible conversions between CSV <-> JSON, such as nested objects with depth.

What reasons would you see to approach the problem differently ?

**Comment by JeyRathnam** [comment]
Hello, 
Can I work on this?

**Comment by christoshadjiaslanis** [comment]
Hey @JeyRathnam . For sure! If you need any pointers you can ask here or on Discord :)

**Comment by JeyRathnam** [comment]
I plan to use [crate](https://docs.rs/csv/1.1.6/csv/) to parse csv. To check if the csv file has headers, I plan to implement something similar to the one in python [csv.py](https://github.com/python/cpython/blob/3.9/Lib/csv.py#L383). The csv crate doesnt have that afaik, it probably would be ideal if it existed in the csv crate. Thoughts?

To integrate it into synth, I think its straighforward implementation similar to file or stdin import/export strategies.

**Comment by llogiq** [comment]
:+1: to the csv crate; it's as great as everything from Andrew. Regarding header detection, I have done something similar in a previous job where we dealt with CSV files, but soon deactivated it because guessing will inevitably come up with the wrong answer every now and then and debugging the cause tends to be more painful than just requiring a configuration or command line flag.

**Comment by OLUWAMUYIWA** [comment]
@JeyRathnam  are you working on this?

**Comment by WiredSound** [comment]
I'm planning to begin working on this issue shortly if I may.
