### ISSUE TITLE
Remove the deny(warnings) annotation

### ISSUE THREAD

**Issue by christoshadjiaslanis** [getsynth/synth#36]
**Describe the bug**
Not a bug - but the `deny(warnings) ` annotation is considered an [anti-pattern](https://rust-unofficial.github.io/patterns/anti_patterns/deny-warnings.html). 

The `deny(warnings)` annotation should be removed from the crates `synth` `synth-gen` and `synth-core`.

There should instead be explicit warning checks in CI with something like `RUSTFLAGS="-D warnings" cargo build`.

**Comment by robert-monk** [comment]
Hi, I would like to help out with this issue!

**Comment by christoshadjiaslanis** [comment]
Hey! That would be much appreciated. 

Let me know if you need anything :)
