### ISSUE TITLE
Synth import extension for creating DB schema level collections and filter out non table objects

### ISSUE THREAD

**Issue by hembhav** [getsynth/synth#40]
**Required Functionality**

Proposing adding schema to  synth import command to build a data model from your Postgres database schema. Currently it goes to public schema and works but need a way to specify schema. Also, when it finds non table objects in schema, it continues to fail. I had to remove those objects temporarily for import to work. 

$ synth import tpch --from postgres://user:pass@localhost:5432/tpch
Building customer collection...
Building primary keys...
Building foreign keys...
Ingesting data for table customer...  10 rows done.

**Proposed Solution**
Provide a switch for selecting schema from existing database.  If you can also add functionality to add table section would be super. 
Besides while selecting schema, based on integrity constraints, if it can add dependencies to collection automatically would help save lots of development time. 

**Use case**
Have many schema in existing database and would like to select schema. It continues to fail when it encounters non table kind of objects. Also, adding integrity constraints to each collection is very laborious task.

**Comment by christoshadjiaslanis** [comment]
@hembhav Thank you for this!

1. Specify the schema name
I'm not sure there is a canonical way to do this in the general case.

I think JDBC does something along the lines of: `postgres://user:password@host/dbname?search_path=schema`. I'm would be happy with this as an implementation as we probably don't want cli flags like `--schema` - as this behavior will vary across datasources.

2.Picking up non-table objects

Could you expand a bit on the type of objects it is picking up on? Is this UDFs for example?

3. Adding integrity constraints to each collection is very laborious task

I assume here that you're referring to having to manually change generators in the JSON by hand. If that is the case - we'll soon be adding inference which will automatically pick up on a lot of this.

If you can confirm 1,2 and 3 we can open up specific issues for them.

**Comment by hembhav** [comment]
Hi,

Please see below. Also I asked for defining rows for individual collections.

Sent from my iPhone

On Jul 9, 2021, at 12:21 PM, Christos Hadjiaslanis ***@***.***> wrote:

﻿

@hembhav<https://github.com/hembhav> Thank you for this!

  1.  Specify the schema name
I'm not sure there is a canonical way to do this in the general case.

Agreed.

I think JDBC does something along the lines of: ***@***.***/dbname?search_path=schema. I'm would be happy with this as an implementation as we probably don't want cli flags like --schema - as this behavior will vary across datasources.

I have tried this method already, but it does not work. It says no matches found. I tried many combination with search_path.  I also changed user search path and make sure has access to schema as well.

2.Picking up non-table objects

Could you expand a bit on the type of objects it is picking up on? Is this UDFs for example?

No. This is for DB. I hadsqlserver sysobjects global table that it kept failing in. After dropping the table it worked.

  1.  Adding integrity constraints to each collection is very laborious task

I assume here that you're referring to having to manually change generators in the JSON by hand. If that is the case - we'll soon be adding inference which will automatically pick up on a lot of this.

Yes. That is correct.

If you can confirm 1,2 and 3 we can open up specific issues for them.

**Comment by christoshadjiaslanis** [comment]
Unfortunately I [don't think](https://docs.rs/postgres/0.19.1/postgres/config/struct.Config.html) the `postgres` crate support specifying the schema in the uri. 

[This discussion](https://github.com/sfackler/rust-postgres/issues/631) is slightly more illuminating on the matter.

We can introduct a `--schema` switch though this is not ideal given that the same command is used for other databases  (aka Mongo or MySQL where schema means something different.)

**Comment by hembhav** [comment]
I played around this further more. I was able to resolve issue with Postgres by changing user default search path from database side. Synth import command takes first search path for Postgres user mentioned and try to generate data. It fails, when it does not find collection in first default schema mentioned in user search path.
One way is to resolve issue by changing user default search path to schema where data needs to be imported. 
  - alter user username set seach_path=importschema, public;
  - synth import workspace -- from postgres://uid:pwd@host:port/dbname

Second way is suggestion to enhance synth import code allow standard search_path postgres connection parameter followed by database for Postgres database type.  Seach_path  can be part of connect string which would  require parsing and set default path for user session at a runtime to generate data for specific schema.
 -- synth import workspace -- from postgres://uid:pwd@host:port/dbname?search_path=importschema

Thanks

**Comment by karthi109457** [comment]
> I played around this further more. I was able to resolve issue with Postgres by changing user default search path from database side. Synth import command takes first search path for Postgres user mentioned and try to generate data. It fails, when it does not find collection in first default schema mentioned in user search path.
> One way is to resolve issue by changing user default search path to schema where data needs to be imported.
> 
> * alter user username set seach_path=importschema, public;
> * synth import workspace -- from postgres://uid:pwd@host:port/dbname
> 
> Second way is suggestion to enhance synth import code allow standard search_path postgres connection parameter followed by database for Postgres database type. Seach_path can be part of connect string which would require parsing and set default path for user session at a runtime to generate data for specific schema.
> -- synth import workspace -- from postgres://uid:pwd@host:port/dbname?search_path=importschema
> 
> Thanks

Hi @hembhav I'm facing similar issue with synth import could you please help

**Comment by hembhav** [comment]
What’s the error you get?

Sent from my iPhone

On Jul 29, 2021, at 12:31 PM, karthi109457 ***@***.***> wrote:

﻿

I played around this further more. I was able to resolve issue with Postgres by changing user default search path from database side. Synth import command takes first search path for Postgres user mentioned and try to generate data. It fails, when it does not find collection in first default schema mentioned in user search path.
One way is to resolve issue by changing user default search path to schema where data needs to be imported.

  *   alter user username set seach_path=importschema, public;
  *   synth import workspace -- from ***@***.***:port/dbname

Second way is suggestion to enhance synth import code allow standard search_path postgres connection parameter followed by database for Postgres database type. Seach_path can be part of connect string which would require parsing and set default path for user session at a runtime to generate data for specific schema.
-- synth import workspace -- from ***@***.***:port/dbname?search_path=importschema

Thanks

Hi @hembhav<https://github.com/hembhav> I'm facing similar issue with synth import could you please help

**Comment by hembhav** [comment]
> > I played around this further more. I was able to resolve issue with Postgres by changing user default search path from database side. Synth import command takes first search path for Postgres user mentioned and try to generate data. It fails, when it does not find collection in first default schema mentioned in user search path.
> 
> > One way is to resolve issue by changing user default search path to schema where data needs to be imported.
> 
> > 
> 
> > * alter user username set seach_path=importschema, public;
> 
> > * synth import workspace -- from postgres://uid:pwd@host:port/dbname
> 
> > 
> 
> > Second way is suggestion to enhance synth import code allow standard search_path postgres connection parameter followed by database for Postgres database type. Seach_path can be part of connect string which would require parsing and set default path for user session at a runtime to generate data for specific schema.
> 
> > -- synth import workspace -- from postgres://uid:pwd@host:port/dbname?search_path=importschema
> 
> > 
> 
> > Thanks
> 
> 
> 
> Hi @hembhav I'm facing similar issue with synth import could you please help
> 
> 

What happens when u try suggested search path in Postgres?

**Comment by hembhav** [comment]
What happens when u try suggested search path in Postgres?

**Comment by christoshadjiaslanis** [comment]
Hey @hembhav @karthi109457 - this should be fixed as of v0.5.6. It is closed by #164.

You can now do `synth import --from postgres://user:pass@localhost/my_database --schema my_schema my_namespace`.

If there are any other issues let me know :)
