### ISSUE TITLE
Specify output size per collection

### ISSUE THREAD

**Issue by hembhav** [getsynth/synth#41]
**Required Functionality**
Ability to specify number of rows generated for each collection.  

**Proposed Solution**
Currently rows parameter specified divides automatically based on number of collections from internal algo. 
Having number of rows specified for each collection within either collection or using some parameter file at collection level would be nice. 

**Use case**
Have certain tables where we need millions of rows and some tables where only handful of rows to simulate actual database rows.

**Comment by christoshadjiaslanis** [comment]
Hey @hembhav .

I think there is room for a complete overhaul in this section (specifying output sizes). Currently the `--size` flag is the total number of rows (lower bound) and you can specify the 'per-collection' output like this:

```json
{
    "type": "array",
    "length": {
        "type": "number",
        "constant": 100000
    },
    "content": {
        "type": "object"
        ...
    }
}
```

Notice the length of the array is set to `constant: 100000`. This guarantees a minimum of 100000 rows being generated.

Does this help?

**Comment by hembhav** [comment]
Yea this worked.

Sent from my iPhone

On Jul 9, 2021, at 11:51 AM, Christos Hadjiaslanis ***@***.***> wrote:

﻿

Hey @hembhav<https://github.com/hembhav> .

I think there is room for a complete overhaul in this section (specifying output sizes). Currently the --size flag is the total number of rows (lower bound) and you can specify the 'per-collection' output like this:

{
    "type": "array",
    "length": {
        "type": "number",
        "constant": 100000
    },
    "content": {
        "type": "object"
        ...
    }
}

Notice the length of the array is set to constant: 100000. This guarantees a minimum of 100000 rows being generated.

Does this help?

**Comment by christoshadjiaslanis** [comment]
Ok - closing this off then.
