### ISSUE TITLE
Add tests for examples (i.e. bank_db)

### ISSUE THREAD

**Issue by christoshadjiaslanis** [getsynth/synth#44]
**Required Functionality**
Currently we don't have automated tests for our examples (i.e. `bank_db`).

**Proposed Solution**
We should have a step in CI which at least runs a generate on a per-example basis and fails on a non-zero exit code.

**Use case**
As we get more examples it's going to be come harder and harder to maintain them.

**Comment by JeyRathnam** [comment]
Hello, 
Can I work on this?

**Comment by christoshadjiaslanis** [comment]
Hey @JeyRathnam - yeah if you're up for it for sure.

**Comment by JeyRathnam** [comment]
@christoshadjiaslanis Thank you!
My idea is to write a bash script that goes through the folders in examples dir and run generate on each and output if pass or fail. 

Would this work?

**Comment by christoshadjiaslanis** [comment]
My thoughts exactly!

**Comment by brokad** [comment]
Closed by #74.
