### ISSUE TITLE
dyld: Library not loaded: /Users/runner/hostedtoolcache/Python/3.9.4/x64/lib/libpython3.9.dylib

### ISSUE THREAD

**Issue by jlkiri** [getsynth/synth#5]
**Describe the bug**
When I try to run synth binary on macOS I get the following error:

```
dyld: Library not loaded: /Users/runner/hostedtoolcache/Python/3.9.4/x64/lib/libpython3.9.dylib
  Referenced from: /usr/local/bin/synth
  Reason: image not found
zsh: abort      synth
```

**To Reproduce**
1. Run on macOS

```
synth
```

2. See error

```
dyld: Library not loaded: /Users/runner/hostedtoolcache/Python/3.9.4/x64/lib/libpython3.9.dylib
  Referenced from: /usr/local/bin/synth
  Reason: image not found
zsh: abort      synth
```

**Expected behavior**
No error.

**Screenshots**

**Environment (please complete the following information):**
 - OS: macOS
 - Version: Latest

**Additional context**

**Comment by christoshadjiaslanis** [comment]
Hey @jlkiri. Yeah we're aware of this issue - we're going to hopefully move away from linking to Python soon, and use something like `fake-rs` to generate semantic types.

In the meantime, the install should work if you:
a) use brew python
b) [install from source](https://openquery-io.github.io/synth/getting_started/installation). See the `compile from source` section.

**Comment by vijaykiran** [comment]
even installing from source is giving the same error, unfortunately

**Comment by christoshadjiaslanis** [comment]
Hey! 

With the release of `v0.5.0` we've removed our Python dep so you should be good to go!

I'll close the issue in a couple of days if nothing else shows up along these lines.

**Comment by vijaykiran** [comment]
@christoshadjiaslanis  Super! it works now :)
