### ISSUE TITLE
Support postgres json and jsonb types

### ISSUE THREAD

**Issue by pickfire** [getsynth/synth#67]
**Required Functionality**

> import from postgres db

Error: We haven't implemented a converter for jsonb

**Proposed Solution**

Support postgres `json` and `jsonb` types for datasource

**Use case**

Generate the schema? I haven't got import working yet.

**Comment by GideonCS** [comment]
+1, I'd like to be able to import my DB to generate a schema, but lack of JSON support is blocking me.
