### ISSUE TITLE
Error: We haven't implemented a converter for citext

### ISSUE THREAD

**Issue by groogiam** [getsynth/synth#70]
**Describe the bug**
I am attempting to generate data from a postgres database that uses citext and recieve the following error

Error: We haven't implemented a converter for citext

I'm hoping implementing should be pretty straight forward as citext could probably just be treated as a string

**To Reproduce**
synth import ztoDeoAuWw --from postgres://adm:mypass@db:5432/ztoDeoAuWw

1. See error
```
Error: We haven't implemented a converter for citext
```

**Expected behavior**
Citext columns would be treated as any other varchar column

**Environment (please complete the following information):**
 - OS: [e.g. Linux, MacOS, Windows] Linux
 - Version: [e.g. 4.2] 0.5.3

**Comment by fretz12** [comment]
hey @groogiam, I tried your changes in #71, and generating `citext` seemed to work for me. Do you have the snippet of your collections .json or any errors you're encountering?

**Comment by groogiam** [comment]
The collections json generated but I was not able to generate any data. All the generates commands resulted in errors or the tool crashing. Sorry but I don't have the container I used to test on available any more.

**Comment by brokad** [comment]
Hey @groogiam, sorry `synth` did not work for you OOB! We're still ironing out a fair amount of basic problems.

I suspect you've hit two issues at the same time: the first is the lack of support for `citext`, for which your original PR #71 LGTM. The second is a combination of #29  and #121, which we're almost done solving (#49 addressed the first one, #122 will address the second)

I'll update this issue once we're done fixing these!

**Comment by brokad** [comment]
Hey @groogiam, feel free to try again with `v0.5.5` or `master`, all the issues above have been addressed :smile:
