### ISSUE TITLE
Support for mysql/mariadb

### ISSUE THREAD

**Issue by kiklop74** [getsynth/synth#8]
**Required Functionality**
It would be really useful for my work to be able to populate directly MySQL/MariaDb databases.

Something like:

```sh
synth generate tpch --to mysql://user:pass@localhost:3066/mydbname
```

**Proposed Solution**

**Use case**
PostgreSQL or MongoDb are widely used but so are MySQL/MariaDB.

**Comment by christoshadjiaslanis** [comment]
Hey thanks for this. 

I will write a plan for implementation shortly. There are a few pre-requisites that need to be completed first. The APIs which define the integrations (PG, Mongo and now MySQL/MariaDB) need to change in a breaking way. We have an internal issue for this and all this will be made public as soon as we have a little time to open source our dev process.
